# Configuration Settings for C94-M8P device
ntrip_client_ros:
  ros__parameters:
    ntrip_server: "rtk2go.com:2101"
    ntrip_user: "USER"
    ntrip_pass: "PASS"
    ntrip_stream: "jemsundabase"
    nmea_gga: '$GPGGA,130414.090,5824.333,N,01539.236,E,1,12,1.0,0.0,M,0.0,M,,*65'